### ISSUE TITLE
ik mis een thead in je table zie de link naar mdn documentatie

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [xxdaniquee/the-startup-responsive-interactieve-website#1]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/e06d3a1b6ca0b976c8ae36847a82ca49deedb8f1/index.html#L24C15-L70

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

**Comment by xxdaniquee** [comment]
<section class="updays">
                <table>
                    <thead>
                        <tr>
                            <th>Upcoming 5 days</th>
                        </tr>
                    </thead>

https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/fb4ab93fcae6389d6c7e793aabb74c3d2bb4c103/index.html#L25C6-L31C29
