### ISSUE TITLE
Section zonder heading

### ISSUE THREAD

**Issue by lemuelmgsn** [xxdaniquee/the-startup-responsive-interactieve-website#10]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L28-L35

Je hebt hier een section zonder heading.

Oplossing: 
`<h1> <h2> <h3>...` gebruiken
of
Een `<div>` gebruiken in plaats van een `<section>`

**Comment by xxdaniquee** [comment]
Thanks 
ik heb er een article van gemaakt
<article class="updays">

**Comment by KrijnHoetmer** [comment]
Hebben articles niet ook headings nodig? :)
