### ISSUE TITLE
Label "Error"

### ISSUE THREAD

**Issue by lemuelmgsn** [xxdaniquee/the-startup-responsive-interactieve-website#11]
![image](https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/assets/144004180/0f7868c4-1724-43c1-b8f7-2d7cf8d917e1)

https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L92-L96

Een label mag maar 1 input hebben. 

Oplossing:

per input een nieuwe label aanmaken.

Bron:
https://css-tricks.com/html-inputs-and-labels-a-love-story/

**Comment by xxdaniquee** [comment]
Thanks voor de tip :)
Ik heb het iets ander opgelost, namelijk met <form>
<form>
         <label class="news-label">Want to get a daily forecast?</label>
         <input type="email" placeholder="Enter your e-mailaddress" class="nletter" required>
         <input type="submit" value="submit" class="submit">
    </form>
