### ISSUE TITLE
<label> foutje 🔎

### ISSUE THREAD

**Issue by MisahSaid** [xxdaniquee/the-startup-responsive-interactieve-website#12]
**Foutomschrijving:**
Ik heb gezien dat je een foutje hebt gemaakt in `<label>` element op regel 93-96. je gebruikt namelijk twee maal `<input>` in één `<label>`. 

**Huidige code:**
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L93-L96

**Oplossing:**
`<label for="submitBtn">
    <input type="submit" id="submitBtn" class="submit">
</label>
`

**Comment by xxdaniquee** [comment]
Thanks voor de tip :)
Ik heb het iets ander opgelost, namelijk met <form>
<form>
         <label class="news-label">Want to get a daily forecast?</label>
         <input type="email" placeholder="Enter your e-mailaddress" class="nletter" required>
         <input type="submit" value="submit" class="submit">
    </form>
