### ISSUE TITLE
the <type> attribute is unnecessary for JavaScript resources

### ISSUE THREAD

**Issue by Abeeryu** [xxdaniquee/the-startup-responsive-interactieve-website#13]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/9ded92c53ae97560cbb76d4101bfe5ac0df2f69c/index.html#L97

Het is niet nodig om <type> attribuut om te gebruiken in JS.

Bron:

https://rocketvalidator.com/html-validation/a-script-element-with-a-src-attribute-must-not-have-a-type-attribute-whose-value-is-anything-other-than-the-empty-string-a-javascript-mime-type-or-module

**Comment by xxdaniquee** [comment]
Volgens mij klopt deze issue niet helemaal. 
In w3c gaat het namelijk om 'type' in de link naar de JS file en niet om deze regel.
type="application/javascript" src="./java/main.js"
