### ISSUE TITLE
<main> element gebruiken

### ISSUE THREAD

**Issue by Abeeryu** [xxdaniquee/the-startup-responsive-interactieve-website#14]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/9ded92c53ae97560cbb76d4101bfe5ac0df2f69c/index.html#L25-L36

Het is altijd beter en overzichtelijker om <main> voor de bodt te gebruiken. Je kan het boven onder jouw nav gebruiken en boven de article die je hebt gebruikt.

Bron:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element?retiredLocale=nl

![Screenshot 2024-01-22 094740](https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/assets/144008500/3e3e2316-1854-4f29-8372-cce38b548209)

**Comment by xxdaniquee** [comment]
Thanks voor de tip.
Ik gebruik nu main
