### ISSUE TITLE
topper

### ISSUE THREAD

**Issue by MisahSaid** [xxdaniquee/the-startup-responsive-interactieve-website#3]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/e06d3a1b6ca0b976c8ae36847a82ca49deedb8f1/assets/style/style.css#L22-L32

^echt netjes gedaan, vind tof om te zien hoe je met naamgeving grid-area aangeeft

**Comment by xxdaniquee** [comment]
Thanks :)
