### ISSUE TITLE
overzichtelijke html tip

### ISSUE THREAD

**Issue by MisahSaid** [xxdaniquee/the-startup-responsive-interactieve-website#4]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/e06d3a1b6ca0b976c8ae36847a82ca49deedb8f1/index.html#L61-L87

^mijn kleine tipje zou kunnen zijn dat het misschien fijn is om meer annotaties te gebruiken en spaties. Vaak omdat wanneer er meer code bij komt het dan wat onduidelijker word nu is het nog prima stiekem. Maar het zou misschien wel sneller en makkelijker leesbaar zijn om nu al meer spaties of/en annotaties te gebruiken. Hihi maar verder ziet het er goed uit TOPPER HIHI 👷‍♀️

**Comment by xxdaniquee** [comment]
in Progress :)
