### ISSUE TITLE
Interactive website images

### ISSUE THREAD

**Issue by Marwaxhello** [xxdaniquee/the-startup-responsive-interactieve-website#6]
Je hebt zowel breedte als hoogte aan je afbeeldingen toegewezen, maar het lijkt alsof ze een beetje uitgerekt zijn, wat niet prettig is om naar te kijken. Dit kanje ook proberen:

```html
img {
    width: 100%;
    height: auto;
    object-fit: contain; /* Of 'cover' afhankelijk van je voorkeur */
}
```

**Comment by xxdaniquee** [comment]
Bedankt voor de tip.
Voor de afbeeldingen op de mobiele versie heb ik nu dit gebruikt en staat het veel beter op mijn site :)
 .activity-img {
        object-fit: cover;
        width: 100%;
        height: 100%;
    }
