### ISSUE TITLE
Interactive website input tip

### ISSUE THREAD

**Issue by Marwaxhello** [xxdaniquee/the-startup-responsive-interactieve-website#7]
Een suggestie: je kunt ook de 'required'-functie toevoegen om ervoor te zorgen dat gebruikers hun e-mailadres invullen!

```html
<form>
  <label for="email">Email:</label>
  <input type="email" id="email" name="email" required>
  <input type="submit" value="Submit">
</form>
```

**Comment by xxdaniquee** [comment]
Thanks voor de tip :) 
Ik heb het nu zo opgelost
<form>
                    <label class="news-label">Want to get a daily forecast?</label>
                    <input type="email" placeholder="Enter your e-mailaddress" class="nletter" required>
                    <input type="submit" value="submit" class="submit">
                </form>
