### ISSUE TITLE
Ongesloten elementen

### ISSUE THREAD

**Issue by lemuelmgsn** [xxdaniquee/the-startup-responsive-interactieve-website#8]
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L41

ongesloten `<i>` element

https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L13-L28

ongesloten `<div>` element

Je was vergeten deze elementen te sluiten.

**Comment by xxdaniquee** [comment]
afgesloten :)
