### ISSUE TITLE
Onafgesloten element 🐥

### ISSUE THREAD

**Issue by MisahSaid** [xxdaniquee/the-startup-responsive-interactieve-website#9]
**Foutomschrijving:** 
Je hebt `<i>` element gebruikt maar waarschijnlijk vergeten af te sluiten.

**Huidige code:**
https://github.com/xxdaniquee/the-startup-responsive-interactieve-website/blob/83f4b05ab53f0c16dd4b33e120bdc57f9269a7e1/index.html#L41

**Oplossing**: 
`<td><i class="fa-solid fa-droplet"></i></td>`

**Comment by xxdaniquee** [comment]
Afgesloten :)
